### ISSUE TITLE
go through material provided by amal

### ISSUE THREAD

**Issue by taniagoia11** [CUQI-DTU/CUQIpy-Benchmarks#66]
- [x] l1 w1
- [x] l2 w1
- [x] l1w2
- [x] l2w2
- [ ] l3w2
- [ ] l4w2
- [ ] l5w2
- [x] l6w2
- [x] l7w2
- [ ] l1w3
- [ ] l2w3
- [ ] l3w3

**Comment by Naokikiki** [comment]
@Naokikiki
