### ISSUE TITLE
sixmodal benchmark

### ISSUE THREAD

**Issue by taniagoia11** [CUQI-DTU/CUQIpy-Benchmarks#68]
type 0

**Comment by Naokikiki** [comment]
https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-031219-041300

**Comment by taniagoia11** [comment]
- this example is chosen so that it shows how sampling methods can get stuck in local model
- it has no gradient (it will give 1/0 at some point), so we cant compute some sampling methods e.g. NUTS -> a next step is persanolized table automization (user can choose which methods to use)
- try to fic the graph

**Comment by taniagoia11** [comment]
1. Main issue: overflow issue
- in the paper they  say "known up to the normalizing constant" -> there is a constant that everything is divided by, we need to find it 
- choose one value for lests say x and en check our graph with their graph in order to fin the issue
- instead of zero fix we could add a samll value epsilon to sin(y)
- try t make the plot function manually 
- keep the values values between 0 and pi
