### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by Naokikiki** [CUQI-DTU/CUQIpy-Benchmarks#85]
・benchmarks in general/ collection that we are making  
・a link / a qr code that takes them to the repo 
・we need to have a few of each category 
・wolfgang problem 
・project management strategy: introduce to scrum

**Comment by taniagoia11** [comment]
- [ ] clear idea of what we want the poster to show
- [ ] expalin eaxh section in detail with links and ref
- [ ] qr to benchmark project?
- [ ] add images

**Comment by taniagoia11** [comment]
deadline for the first draft; friday the 6th

**Comment by taniagoia11** [comment]
- [ ] Decide on a title for the poster. One suggestion could be: CUQIpy-Benchmarks: A new open-source collection of UQ benchmarking problems  (if too long, can remove one or more of “open-source”, “new” and replace “benchmarking problems” by “benchmarks”). I’d keep “CUQIpy-Benchmarks” in the title to clear convey the collection you built as a key result.

- [ ] Please add Amal, Charlie and me as co-authors.

- [ ] save space: 
-  To save space you can leave out the Department part of author affiliations and include just the University part, and maybe squeeze onto a single line.
- In text, no need to say “Looking at the figure”. Can remove that. Try keep extra brief, and save space, by shortening sentences so they do not spill one or two short words onto another line, as this wastes almost an entire line of space.
- Please keep one CUQI logo, one Villum Logo and add one CUQIpy logo (removing one CUQI and one Villum logo)


- [ ] State explicitly as one of the aims to create a collection of benchmark problems for CUQIpy.

- [ ] The math looks a bit funny, like a weird sometimes bold font. Some of the “x” look like greek “chi” and the mathcal G is too small. Maybe the poster template has specified this font. Is it possible to switch to the standard latex font for math?

- [ ] Tables: Also remove the left and right vertical lines as part of the outer box, keeping only 3 horizontal lines: one at very top, one below headers, and one at very bottom. All three should be bold.

- [ ]  xhange v0 and v1 of ESS and Rhat  to mean. 


- [ ] I suggest splitting the current section 2 into maybe a section defining what benchmarks are including your current “types of benchmarks”, followed by a new section 3 on “Process”, this is such that readers will be told what you mean by benchmarks before being told how to operate your implementation. You could also specifically title this Section 3 on “The CUQIpy-Benchmarks collection” to more clearly emphasize your repo/product and as part of it how to operate it.

- [ ] remove simplest bip formula and add sixmodal

- [ ] Visually, here especially in results, keep things that belong together, together –w.

- [ ] In conclusion, state that the constructed benchmark collection is a resulting outcome, that allowed you to easily carry out benchmarking studies with CUQIpy on the different types of benchmarks, such as the example results presented on the poster.

- [ ] QR code seems very big, can be reduced and moved to bottom corner, maybe together with logos out of the main part of the poster.

- [ ] Please add literature (no more than 4-5 articles).

- [ ] In tables LogPDF\ESS should be LogPDF/ESS to indicate division.
